const weekGames = 
[{"day": "09",
  "games": [{"casted": 2,
             "division": "PCL",
             "end_time": "7:30 PM",
             "location": "Middlefield Ballpark",
             "roles": 2,
             "start_time": "5:30 PM",
             "title": "Say Hey Baseball vs. Venture Construction"}],
  "month": "Aug",
  "weekDay": "Mon"},
 {"day": "10",
  "games": [{"casted": 1,
             "division": "Majors",
             "end_time": "5:30 PM",
             "location": "Middlefield Ballpark",
             "roles": 2,
             "start_time": "3:30 PM",
             "title": "Morgan-Gault vs. Agile"},
            {"casted": 0,
             "division": "PCL",
             "end_time": "7:30 PM",
             "location": "Hoover Park",
             "roles": 2,
             "start_time": "5:30 PM",
             "title": "Midtown Veterinary Hospital vs. Ada's"}],
  "month": "Aug",
  "weekDay": "Tues"},
 {"day": "11",
  "games": [{"casted": 2,
             "division": "Majors",
             "end_time": "6:45 PM",
             "location": "Middlefield Ballpark",
             "roles": 3,
             "start_time": "4:45 PM",
             "title": "Stanford Shopping Center vs. Hengehold"},
            {"casted": 0,
             "division": "PCL",
             "end_time": "7:30 PM",
             "location": "Hoover Park",
             "roles": 2,
             "start_time": "5:30 PM",
             "title": "Eco Office vs. Agile"},
            {"casted": 0,
             "division": "Majors",
             "end_time": "9:00 PM",
             "location": "Middlefield Ballpark",
             "roles": 2,
             "start_time": "7:00 PM",
             "title": "The Old Pro vs. Bike Connection"}],
  "month": "Aug",
  "weekDay": "Wed"},
 {"day": "12",
  "games": [{"casted": 1,
             "division": "Majors",
             "end_time": "7:30 PM",
             "location": "Middlefield Ballpark",
             "roles": 2,
             "start_time": "5:30 PM",
             "title": "Alhouse vs. Bevy"}],
  "month": "Aug",
  "weekDay": "Thur"},
 {"day": 13, "games": [], "month": "Aug", "weekDay": "Fri"},
 {"day": "14",
  "games": [{"casted": 1,
             "division": "Majors",
             "end_time": "1:00 PM",
             "location": "Middlefield Ballpark",
             "roles": 2,
             "start_time": "11:00 AM",
             "title": "Agile vs. Bevy"},
            {"casted": 0,
             "division": "PCL",
             "end_time": "1:30 PM",
             "location": "Hoover Park",
             "roles": 2,
             "start_time": "11:30 AM",
             "title": "Midtown Veterinary Hospital vs. Carmel Imports"},
            {"casted": 2,
             "division": "Majors",
             "end_time": "3:30 PM",
             "location": "Middlefield Ballpark",
             "roles": 2,
             "start_time": "1:30 PM",
             "title": "Bike Connection vs. Alhouse"},
            {"casted": 0,
             "division": "PCL",
             "end_time": "4:00 PM",
             "location": "Hoover Park",
             "roles": 2,
             "start_time": "2:00 PM",
             "title": "Venture Construction vs. Ada's"},
            {"casted": 2,
             "division": "PCL",
             "end_time": "6:00 PM",
             "location": "Hoover Park",
             "roles": 3,
             "start_time": "4:00 PM",
             "title": "Say Hey Baseball vs. Agile"},
            {"casted": 3,
             "division": "Majors",
             "end_time": "6:00 PM",
             "location": "Middlefield Ballpark",
             "roles": 3,
             "start_time": "4:00 PM",
             "title": "Hengehold vs. The Old Pro"},
            {"casted": 1,
             "division": "Majors",
             "end_time": "8:30 PM",
             "location": "Middlefield Ballpark",
             "roles": 2,
             "start_time": "6:30 PM",
             "title": "Morgan-Gault vs. Stanford Shopping Center"}],
  "month": "Aug",
  "weekDay": "Sat"},
 {"day": "15",
  "games": [{"casted": 1,
             "division": "PCL",
             "end_time": "12:00 PM",
             "location": "Hoover Park",
             "roles": 2,
             "start_time": "10:00 AM",
             "title": "Carmel Imports vs. Eco Office"},
            {"casted": 0,
             "division": "Majors",
             "end_time": "5:00 PM",
             "location": "Middlefield Ballpark",
             "roles": 3,
             "start_time": "3:00 PM",
             "title": "Bike Connection vs. Agile"}],
  "month": "Aug",
  "weekDay": "Sun"}]

export default weekGames