export {
    faUser,
    faBaseballBall,
    faChevronUp,
    faChevronDown,
    faChevronLeft,
    faChevronRight,
    faWrench,
    faUserAlt,
    faExclamationCircle,
    faCheckCircle,
    faBan,
    faSortDown,
    faMedal,
    faMeteor,
    faMountain,
    faPlus,
    faSquare,
    faEdit,
    faPenSquare,
    faCheck,
    faTimes,
    faFire,
    faUserSlash,
    faLink,
    faBars,
    faTrash,
    faPlusSquare,
    faFilePdf,
    faFileCsv,
    faFileExcel,
    faTable,
    faEnvelope,
    faCommentDots,
    faUsers,
    faSpinner,
    faLock,
    faLayerGroup,
    faPen,
    faClock,
    faBell,
    faBullhorn,
    faSync,
    faSearch,
    faEllipsisH
} from "@fortawesome/free-solid-svg-icons"

export {
    faEnvelope as farFaEnvelope,
    faPlusSquare as farFaPlusSquare,
    faPaperPlane as farFaPaperPlane,
    faCalendarCheck as farFaCalendarCheck,
} from "@fortawesome/free-regular-svg-icons"

export {
    faGoogle,
    faFacebookF
} from "@fortawesome/free-brands-svg-icons"
